DROP TABLE IF EXISTS comments;

CREATE TABLE comments(
    id SERIAL PRIMARY KEY,
    user_id VARCHAR NOT NULL,
    comment VARCHAR NOT NULL,
    image_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
